version: '3.9'
services:
  backend: 
    container_name: crypto-backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports: 
      - 4000:3000
    env_file: backend/.env
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
       - backend/.env
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080